# Generated by Django 4.1.4 on 2022-12-19 15:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to=blog.models.BlogBanner.get_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('photo', models.ImageField(upload_to=blog.models.Blog.get_file_name)),
                ('data', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=200)),
                ('text', models.TextField(default='Input text', max_length=5000)),
            ],
            options={
                'ordering': ('-data',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
