# Generated by Django 4.1.4 on 2022-12-19 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('created', 'Створений'), ('paid', 'Оплачений'), ('shipped', 'Відправлений'), ('canceled', 'Відмінений')], default='created', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(choices=[('Ukraine', 'Україна'), ('Poland', 'Польша'), ('Moldova', 'Молдова')], default=False, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.PositiveIntegerField(default=False, max_length=10)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
